- name: Find the files
  hosts: all
  become: yes
  tasks:
    - find:
        paths: /opt/apache-tomcat-9.0.10/webapps
        file_type: any
      register: out

    - debug:
        msg: "{{out}}"

    