- name: Demo on handlers
  hosts: APPNODES
  become: yes
  tasks:
    - name: Install web server 
      package: 
        name: httpd
        state: installed
      notify: restart httpd service

  handlers:
    - name: restart httpd service
      service:
        name: httpd
        state: restarted
        
